# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d698aba00d3662a2328d0c7cdfce00c0ea1dea7829f6878b66343d595711ac1d8a46029708698459eea640372dcf70cb2011465e02b977788376d8fa62b56fb

test:
  secret_key_base: 8c6a38106fab64a6f093ce84712de0b3574a9160a33554df725201714068a7599938381eb67ecb950daed9f7972cb6850be058f4ea2f90c1c71073bbd95678c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
